# Configuration file for the tagmap pipeline
# Path to the .tsv file containing the samples information: sample name and paths to the fastq files
# Entries with the same sample name will be merged
samples_path: 'config/samples.tsv'
refgen_path: '../../../mm10_custom.fa'
chrom_sizes_path: '../../../mobilization_mapping/mm10_custom_chromsizes.txt'

# Chromsizes with just the original genome, without the cassette, to use for UCSC visualization
chrom_sizes_path_no_cassette: '../../../genomes/mm10/chromsizes.txt'
# Path to the blacklist file: any peak overlapping this file will be removed
# Simply delete this line if you don't have a blacklist
blacklist: 'resources/blacklist_mm10_PB.bed'

mapper: 'bwa-mem2'

dedup: True

cassette_name: 'mobilized_enhancer'
# Sequence of the primers used to amplify the cassette
# If multiple PCRs were used, use the sequence of the primers used in the last step
forward_primer_sequence: 'GTACGTCACAATATGATTATCTTTCTAG'
reverse_primer_sequence: 'CGTCAATTTTACGCAGACTATC'
# 5' overhang of the primers above, likely Nextera N7 sequence
primer_overhang: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'
# Sequence of the adapters loaded onto Tn5 transposase, likely Nextera N5 sequence
# Not used at the moment
# adapter_seq: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'

insertion_seq: "TTAA"

use_junction_readthrough: False

# Peak calling
min_peak_width: 200
min_peak_reads: 10
min_peak_frac: 0.01
min_peak_dist: 1000

fastq_folder: '../Data/Raw/T1/fastq/'
bams_folder: '../Data/Processed/T1/bams/'
pairs_folder: '../Data/Processed/T1/pairs/'
coverage_folder: '../Data/Processed/T1/coverage/'
peaks_folder: '../Data/Processed/T1/peaks/'
insertion_sites_folder: '../Data/Processed/T1/insertion_sites/'