# Configuration file for the tagmap pipeline
# Path to the .tsv file containing the samples information: sample name and paths to the fastq files
# Entries with the same sample name will be merged
samples_path: 'config/samples.tsv'
refgen_path: '../../../mm10_custom.fa'
chrom_sizes_path: '../../../mobilization_mapping/mm10_custom_chromsizes.txt'

# Chromsizes with just the original genome, without the cassette, to use for UCSC visualization
chrom_sizes_path_no_cassette: '../../../genomes/mm10/chromsizes.txt'
# Path to the blacklist file: any peak overlapping this file will be removed
# Simply delete this line if you don't have a blacklist
blacklist: 'resources/blacklist_mm10_PB.bed'

mapper: 'bwa-mem2'

dedup: True

cassette_name: 'mobilized_enhancer'
# Coordinate of the 5' of the PCR1 primer
# alignments with 5' end +- 10 bp of this coordinate will be kept
reverse_ITR_primer_position: 33
forward_ITR_primer_position: 6001
insertion_seq: "TTAA"

use_junction_readthrough: False

# Peak calling
min_peak_width: 200
min_peak_reads: 10
min_peak_frac: 0.01
min_peak_dist: 1000

output_dir: '../Data/Processed/'